-- phpMyAdmin SQL Dump
-- version 4.9.5deb2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 01, 2023 at 02:10 PM
-- Server version: 8.0.33-0ubuntu0.20.04.2
-- PHP Version: 7.4.3-4ubuntu2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rebellug`
--

-- --------------------------------------------------------

--
-- Table structure for table `collaborations`
--

CREATE TABLE `collaborations` (
  `id` int NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `banner_pic` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `page` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `collaborations`
--

INSERT INTO `collaborations` (`id`, `title`, `banner_pic`, `logo`, `release_date`, `location`, `page`) VALUES
(1, 'The Laceropes Mission', 'laceropes.jpg', 'laceropes_logo.png', '2019-06-22', 'Brickworld Chicago and Online', 'laceropes'),
(2, 'Thrawn: Grand Admiral Rising', 'thrawn.jpg', 'thrawn_logo.png', '2018-11-08', 'Online', 'thrawn'),
(3, 'The Star Wars Zoo', 'starwarszoo.jpg', 'null', '2018-06-18', 'Brickworld Chicago', 'zoo'),
(4, 'Clones Alone', 'clonesalone.jpg', 'clonesalonelogogray.png', '2015-12-06', 'Online', 'clonesalone'),
(5, 'Attack on Ryloth', 'attackonryloth.jpg', 'null', '2016-06-18', 'Brickworld Chicago', 'ryloth'),
(6, 'Order 66', 'order66.jpg', 'null', '2017-04-07', 'Online', 'order66'),
(7, 'The Scarif Tower', 'scarif.jpg', 'null', '2017-06-17', 'Brickworld Chicago', 'scarif'),
(8, 'Maul: Son of Dathomir', 'sonofdathomir.jpg', 'sonofdathomirlogo.png', '2017-10-08', 'Online', 'sonofdathomir'),
(9, 'Kingdoms at War', 'kingdomsatwar.jpg', 'kingdomsatwarlogo.png', '2018-03-05', 'Online', 'kingdomsatwar'),
(10, 'Bree and Buckleberry Ferry', 'bree.jpg', 'null', '2018-04-28', 'På Kloss Hold', 'bree'),
(11, 'So Uncivilized', 'SoUncivilizedAnnouncement.jpg', 'SoUncivilizedBlack.png', '2020-07-03', 'Online', 'souncivilized');

-- --------------------------------------------------------

--
-- Table structure for table `contests`
--

CREATE TABLE `contests` (
  `id` int NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `banner_pic` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `page` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `contests`
--

INSERT INTO `contests` (`id`, `title`, `banner_pic`, `logo`, `release_date`, `location`, `page`) VALUES
(1, 'Battlefront', 'battlefront.jpg', 'null', '2017-08-19', 'Online', 'battlefront.php'),
(2, 'Rogue One', 'rogueonecontest.jpg', 'null', '2017-12-17', 'Online', 'rogueone.php'),
(3, 'Solo', 'solo.jpg', 'solologo.png', '2018-05-28', 'Online', 'solo.php'),
(4, 'Grid Wars', 'gridwars.jpg', 'gridwarslogo.png', '2018-10-04', 'Online', 'gridwars.php'),
(5, 'Vignweek', 'vignweek2019.png', 'null', '2019-11-03', 'Online', 'vignweek2019.php'),
(6, 'Assemble the Fleet', 'assemblethefleet.jpg', 'assemblethefleetlogo.png', '2020-02-02', 'Online', 'assemblethefleet.php'),
(7, 'Vignweek', 'vignweek2020.jpg', 'null', '2020-05-29', 'Online', 'vignweek2020.php'),
(8, 'Vignweek', 'Vignweek_2021.jpg', 'null', '2021-06-14', 'Online', 'vignweek2021');

-- --------------------------------------------------------

--
-- Table structure for table `instructions`
--

CREATE TABLE `instructions` (
  `id` int NOT NULL,
  `title` varchar(128) DEFAULT NULL,
  `builder_id` int DEFAULT NULL,
  `description` varchar(5000) DEFAULT NULL,
  `price` varchar(128) DEFAULT NULL,
  `paypal_link` varchar(128) DEFAULT NULL,
  `pic_0` varchar(128) DEFAULT NULL,
  `pic_1` varchar(128) DEFAULT NULL,
  `pic_2` varchar(128) DEFAULT NULL,
  `pic_3` varchar(128) DEFAULT NULL,
  `pic_4` varchar(128) DEFAULT NULL,
  `pic_5` varchar(128) DEFAULT NULL,
  `pic_6` varchar(128) DEFAULT NULL,
  `pic_7` varchar(128) DEFAULT NULL,
  `pic_8` varchar(128) DEFAULT NULL,
  `pic_9` varchar(128) DEFAULT NULL,
  `xml_parts_list` varchar(128) DEFAULT NULL,
  `display` varchar(10) DEFAULT NULL,
  `manual_order` int DEFAULT NULL,
  `thumbnail` varchar(128) DEFAULT NULL,
  `isC4C` varchar(10) DEFAULT NULL,
  `C4CPercent` int DEFAULT NULL,
  `free` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `instructions`
--

INSERT INTO `instructions` (`id`, `title`, `builder_id`, `description`, `price`, `paypal_link`, `pic_0`, `pic_1`, `pic_2`, `pic_3`, `pic_4`, `pic_5`, `pic_6`, `pic_7`, `pic_8`, `pic_9`, `xml_parts_list`, `display`, `manual_order`, `thumbnail`, `isC4C`, `C4CPercent`, `free`) VALUES
(1, 'HAVw A6 Juggernaut', 22, 'I present to you the HAVw A6 Juggernaut, or more commonly known as the Clone Turbo Tank. This monster of machine was primarily used by the Galactic Republic but later saw shorter service under the Galactic Empire. It was a reliable and deadly weapon and became mostly famous for participating in the battle at Kachirho beach on Kashyyyk.\r\n\r\nThis custom model contains 7190 Lego pieces with a little bit over 450 unique parts. To be able to make these 7000+ pieces take the shape of the juggernaut you will have to take the aide of a 1400-step manual. It includes the instructions for the whole build along with two wheel designs you can choose from. With the purchase of this manual you also get the parts lists for the tank along with free instruction access to any future updates I do to the model. If any questions or constructive criticism pops up while building feel free to email me at <a href=\"mailto:brickpuke@gmail.com\">brickpuke@gmail.com</a>\r\n\r\nThis is a custom model and it is recommended builders have previous experience with building LEGO models and can easily handle LEGOs own instructions. The Juggernaut is extremely sturdy throughout the whole model, with the weakest point being the wheels. With the instructions there is an updated version of the wheels included that handle the weight of the Juggernaut’s body much better. If you plan on rolling the tank I recommend you build that design. But I personally still don’t recommend you drive it. This is primarily a design for displaying and not for playing with, although it does have a couple of cool functions to it. <a href=\"https://www.youtube.com/watch?v=GCmLNxlIPZc\">Here is a full showcase video</a>.', '29.00', 'http://rebellug.fetchapp.com/sell/7ae8bde2', 'juggernaut-1.jpg', 'juggernaut-2.jpg', 'juggernaut-3.jpg', 'juggernaut-4.jpg', 'juggernaut-5.jpg', 'juggernaut-6.jpg', 'tank_in_laceropes.jpg', NULL, NULL, NULL, 'juggernaut/index.html', 'true', 2, 'juggernaut-1.jpg', 'true', 100, NULL),
(2, 'Republic Attack Gunship (LAAT/i)', 11, 'The Republic Attack Gunship, or Low Altitude Assault Transport/infantry (LAAT/i), was used widely throughout the Clone Wars as transport for clone troopers through the battlefield while providing heavy air support.\r\n\r\nThis model is 2,414 pieces. It fits minifigures inside the cockpit and hangar bay, has working doors and a back loading ramp, and poseable cannons located at the very front and back. The instructions also come with directions for an angled display stand. Although it is definitely designed as a display model as far as LEGO sets go, and the build process can become complex and difficult, it is quite solid once it\'s all clicked together.\r\n\r\nFor more details, I recommend checking out my <a href=\"https://www.youtube.com/watch?v=3Zvgsgm3kVk\">YouTube video</a>.', '10.00', 'http://rebellug.fetchapp.com/sell/dc82367c', 'republic_gunship_laser_storm_background_front_angle.jpg', 'republic_gunship_laser_storm_background_back_angle.jpg', 'example_instructions_page.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RebelLUG_Republic_Gunship_Instructions_2020-8-31.xml', 'true', 2, 'republic_gunship_laser_storm_background_front_angle.jpg', 'ture', 50, NULL),
(3, 'Jyn Erso\'s A180 Blaster Pistol', 7, 'So Uncivilized: RebelLUG Blaster Collab model. The A180 Blaster Pistol is a pistol used by Jyn Erso in Rogue One and is also in Star Wars Battlefront (2015). Features a moving trigger. While stable enough for light play, this model is intended for display. Instructions are for the blaster only.', '12.00', 'http://rebellug.fetchapp.com/sell/2ed3bed9', 'a180main.jpg', 'A180_03 - Nick Brick.jpg', 'NickBrickA180 - Nick Brick.gif', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NickBrickA180Parts - Nick Brick.xml', 'true', 3, 'a180main.jpg', 'true', 100, NULL),
(4, 'Appa (Avatar)', 7, 'Microscale flying bison, Appa, from Avatar: The Last Airbender. Head, tail, and legs move.', '5.00', 'http://rebellug.fetchapp.com/sell/1685b596', 'appamain.jpg', 'NickBrickAvatarAppa_2_NB - Nick Brick.jpg', 'NickBrickAvatarAppa_NB - Nick Brick.jpg', 'NickBrickAvatarAppaTurnaround - Nick Brick.gif', NULL, NULL, NULL, NULL, NULL, NULL, 'Nick Brick Appa - Nick Brick.xml', 'true', 4, 'appamain.jpg', 'true', 100, NULL),
(5, 'AT-RT', 36, 'The All Terrain Recon Transport, better known as the AT-RT served the Grand Army of the Republic during the Clone Wars. This LEGO® model is perfect for display, seating 1 minifigure. The legs are fully articulated, allowing for a wide variety of poses.', '1.00', 'http://rebellug.fetchapp.com/sell/84b05fa8', 'frontatrt.jpg', 'backatrt.jpg', 'AT-RT_spin.gif', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AT-RT_All_Terrain_Recon_Transport.xml', 'true', 4, 'atrt thumb.jpg', 'true', 100, NULL),
(6, 'Baby Walker', 29, 'The most powerful infant in the galaxy has entered the game. Si-Bored Industries has recently expanded its artillery from the traditional drones and obsolete \"adult-sized\" exosuits to toddlers ready to throw the ultimate tantrum. Except now, there\'s no pacifying this 46 piece monster.', '2.00', NULL, 'main_baby_walker.jpg', 'render.PNG', 'instructions.PNG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'baby_at-rt.xml', 'false', NULL, 'main_baby_walker.jpg', NULL, NULL, NULL),
(7, 'CR-2 Heavy Blaster Pistol', 21, 'So Uncivilized: RebelLUG Blaster Collab model. The CR-2 Heavy Blaster Pistol was first introduced in Star Wars Episode I The Phantom Menace and then prominently featured in 2017\'s Star Wars Battlefront II. This 2350 parts 1:1 replica has a functional trigger and is strong enough to be held and moved around easily. Instructions for a display stand are also included.', '15.00', 'http://rebellug.fetchapp.com/sell/976d7d32', 'CR-2_9.3.1 - Andrew Cazenave-Tapie.jpg', 'CR-2_19.3 - Andrew Cazenave-Tapie.jpg', 'CR-2_14.3.1 - Andrew Cazenave-Tapie.jpg', 'CR-2_13.3.1 - Andrew Cazenave-Tapie.jpg', 'CR-2_10.3.1 - Andrew Cazenave-Tapie.jpg', NULL, NULL, NULL, NULL, NULL, 'cr-2 - Andrew Cazenave-Tapie.xml', 'true', 3, 'CR-2_9.3.1 - Andrew Cazenave-Tapie.jpg', 'true', 40, NULL),
(8, 'DC-17S Blaster Pistol', 24, 'This model is a 1:1 scale replica of the DC-17S Blaster Pistol which was dual-wielded by Captain Fordo in Star Wars: Clone Wars, the beloved animated series from 2003. This model is sturdy enough to be held in hand and makes a great display piece when placed on its stand, which is complete with a brick-built Republic insignia.', '8.00', 'http://rebellug.fetchapp.com/sell/c2767e45', 'DC-17S Blaster Pistol Cover photo 2 - Peter S.jpg', 'DC-17S blaster rotating_partslist 2_2 - Peter S.gif', 'DC-17S Blaster Pistol Cover Photo - Peter S.JPG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DC-17S blaster rotating_partslist - Peter S.xml', 'true', 3, 'DC-17S Blaster Pistol Cover photo 2 - Peter S.jpg', 'ture', 100, NULL),
(9, 'Din Djarin\'s Blaster Pistol', 17, 'A 1:1 replica of the blaster pistol used by Din Djarin in The Mandalorian series, includes instructions for blaster and stand, features a working trigger.', '10.00', 'http://rebellug.fetchapp.com/sell/a37d7567', '20200810_161516000_iOS 2 - Lego Fin..jpg', 'Mando blaster with stand gif_2 - Lego Fin..gif', '20200811_114716000_iOS - Lego Fin..jpg', '20200811_115303000_iOS - Lego Fin..jpg', NULL, NULL, NULL, NULL, NULL, NULL, 'Mandalorian blaster - Lego Fin..xml', 'true', 3, 'dinmainpage.jpg', 'true', 50, NULL),
(10, 'Han Solo\'s DL-44 Blaster Pistol', 7, 'So Uncivilized: RebelLUG Blaster Collab model. Replica of Han Solo\'s DL-44 Blaster Pistol from Star Wars Episode IV: A New Hope. Features a moving trigger. While stable enough for light play, this model is intended for display. Instructions are for the blaster only', '12.00', 'http://rebellug.fetchapp.com/sell/edb08cd0', '01Main - Nick Brick.jpg', 'NickBrickDL44 - Nick Brick.gif', '09FPS2 - Nick Brick.jpg', '07Table - Nick Brick.jpg', NULL, NULL, NULL, NULL, NULL, NULL, 'NickBrickDL44Parts - Nick Brick.xml', 'true', 3, '01Main - Nick Brick.jpg', 'true', 100, NULL),
(11, 'KOTOR Ebon Hawk', 21, 'The Dynamic-Class Freighter better known as the Ebon Hawk was the space ship used by Revan and the famous jedi Bastila Shan to travel around the galaxy in the attempt of defeating former apprentice Malak who had become a very powerful sith lord. This ship was featured on the video game Star Wars: Knights of the Old Republic. This Model composed of 3179 pieces has a detailed and accurate outside that mixes many building techniques. This model also has a full interior that can be accessed by opening the side panels and removing the top of the hull. The interior includes a cockpit with four sits, a communications area, the main hold, two barracks, two cargo holds, an engine room, a deployable boarding ramp, a small medical area and the turret access which can be uncovered by removing the detachable main turret on the top. On top of that, it includes a display stand with a custom UCS plaque (custom sticker included with instructions) and two minifigures: Carth Onasi and T3-M4.', '15.00', 'http://rebellug.fetchapp.com/sell/1f172ffc', 'EH_v.RL - Andrew Cazenave-Tapie.jpg', 'Ebon Hawk - Andrew Cazenave-Tapie.gif', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EbonHawk.xml', 'true', 5, 'EH_v.RL - Andrew Cazenave-Tapie.jpg', 'true', 40, NULL),
(12, 'ELG-3A Blaster Pistol', 38, 'An elegant hold-out pistol for diplomats of Naboo, manufactured by Merr-Sonn Munitions. Built by Masked Builder for the 2020 RebelLUG Blaster Collab', '2.50', 'http://rebellug.fetchapp.com/sell/94f756f2', 'padmeblaster - Masked Builder.jpeg', 'padmeblaster - Masked Builder.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'padmeblaster - Masked Builder.xml', 'true', 3, 'pademthumb.jpg', 'true', 100, NULL),
(13, 'Republic Fighter Tank', 12, 'The TX-130 Saber-class Fighter Tank, commonly known as the Republic Fighter Tank. This is designed as minifig scale and has 380 parts. The tank has adjustable cannons, and secondary gun. The back ailerons are also adjustable. This build is about 7in X 5in X 3½in. This was designed primarily as a display model. It fairly stable, but not strong enough/designed for play. There is an area for a gunner to stand, but there is not room for a pilot. The second picture shows stickers from set #75182 that have been cut to fit the new model.', '8.00', 'http://rebellug.fetchapp.com/sell/dadc3ad0', 'RFTMainPhoto.jpg', 'RFT3Dgif.gif', 'RFTInstructionPage.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'fighter_tank_parts.xml', 'true', 4, 'RFTMainPhoto.jpg', 'true', 50, NULL),
(14, 'The Last Word', 7, 'Exotic hand cannon appearing in Destiny and Destiny 2. Features moving trigger and swivel-out cylinder with removable cartridge. Intended as a display model but can be carefully held one-handed. Two XMLs are provided for parts lists. One contains official LEGO 1x1 tiles with letter prints, and the other contains parts for a blank side barrel. There is a significant cost difference between these two versions.', '12.00', 'http://rebellug.fetchapp.com/sell/083d69ba', 'LWmain.JPG', 'LWfront.jpg', 'LWback.jpg', 'LWlay.jpg', 'LWunload.jpg', NULL, NULL, NULL, NULL, NULL, 'last-word/index.html', 'true', 2, 'LWfront.jpg', 'true', 100, NULL),
(15, 'Mandalorian WESTAR-35 Blaster Pistol', 11, 'This was made as part of RebelLUG\'s 2020 Summer collaboration, So Uncivilized, a collection of 1:1 scale Star Wars blasters. I made dual WESTAR-35 blaster pistols, which were most commonly used by the Mandalorians, such as Pre Viszla and the Death Watch in Star Wars: The Clone Wars.\r\n\r\nIt\'s strong enough to hold and move around and the trigger has a spring mechanism in it, so it actually actuates.\r\n\r\nI made two of them, and I built a stand to display both together. Instructions for the dual pistol stand are included, however if you only plan to build one of them, I suggest designing a new stand.', '8.00', 'http://rebellug.fetchapp.com/sell/e3a1b23a', 'westar-35_blaster_pistol_cross_2.jpg', 'westar-35_blaster_pistol_front_angle.jpg', 'westar-35_blaster_pistol_back_angle.jpg', 'westar-35_blaster_pistol_side_profile.jpg', NULL, NULL, NULL, NULL, NULL, NULL, 'westar-35/index.html', 'true', 3, 'westar-35_blaster_pistol_front_angle.jpg', 'true', 50, NULL),
(16, 'Coruscant Police Speeder', 21, 'The Coruscant Police Speeder or Panther Police Interceptor is an airspeeder used by police officers and police droids for patrolling and law enforcement operations in the capital of the Republic and later the Galactic Empire, Coruscant. it was manufactured by SoroSuub Corporations during the Clone Wars and the early stages of the Galactic Civil War. This model composed of 373 parts was built as a highly detailed and sturdy display piece that can be used to complement a wide variety of Coruscant themed MOCs, even though it cannot fit any minifigures because of the core structure of the vehicle, it captures very well the exterior looks of the original Star Wars design. Note: all four 89762 should be replaced by part 89762pb03', '3.00', 'http://rebellug.fetchapp.com/sell/1f4fc296', 'courscantpolicemain.JPG', 'policespeeder360.gif', 'policespeederinstruct.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'policespeeder_parts.xml', 'true', 5, 'courscantpolicemain.JPG', 'true', 40, NULL),
(17, 'Aliens M41A Pulse Rifle', 7, 'Pulse Rifle issued to the Colonial Marines in the film Aliens. Features two moving triggers, removable magazine, sliding charging handle, working pump action, and optional light-up ammo counter (powered by Brickstuff). Can be held one handed but it\'s ideal to carry two-handed. Instructions show how to make the Pulse Rifle with one magazine and one underbarrel grenade.\r\n\r\nBrickstuff needed for light-up ammo counter:&ensp;<a href=\"https://www.brickstuff.com/store/p13/Warm_White_LED_Strips_and_Connecting_Cables_%282-Pack%29_for_LEGO%C2%AE_Models.html\">LED x1</a>&emsp;<a href=\"https://www.brickstuff.com/store/p31/Coin_Cell_Battery_Pack_with_On%2FOff_Switch_for_the_Brickstuff_LEGO%C2%AE_Lighting_System.html\">Battery x1</a>', '15.00', 'http://rebellug.fetchapp.com/sell/928bbe29', 'pulseriflemain.JPG', '09Unload.JPG', '11FPStilted.JPG', '14GrenadeHeld.JPG', 'NickBrickM41A_Render.jpg', NULL, NULL, NULL, NULL, NULL, 'M41ARifle _parts.xml', 'true', 2, 'pulseriflemain.JPG', 'true', 100, NULL),
(18, 'Puzzle Box 1', 29, 'LEGO® Puzzle box - build these fun little desk buddies and see who can figure out how to unlock the surprise inside! Difficulty level 1 - check out <a href=\"https://rebellug.com/instructions/puzzle-box-2\" target=\"_blank\">Puzzle Box 2</a> for a harder challenge!', '1.00', 'http://rebellug.fetchapp.com/sell/4b941fff', 'Puzzle_Box_1mainphoto.jpg', 'puzzlebox1main.gif', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mario box1.xml', 'true', 3, 'Puzzle_Box_1mainphoto.jpg', 'true', 100, NULL),
(19, 'Puzzle Box 2', 29, 'LEGO® Puzzle box - build these fun little desk buddies and see who can figure out how to unlock the surprise inside! Difficulty level 2 - check out <a href=\"https://rebellug.com/instructions/puzzle-box-1\" target=\"_blank\">Puzzle Box 1</a> for an easier challenge!', '1.00', 'http://rebellug.fetchapp.com/sell/51e0491e', 'Puzzle_Box_2mainphoto.jpg', 'puzzlebox2main.gif', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mario Box2.xml', 'true', 3, 'Puzzle_Box_2mainphoto.jpg', 'true', 100, NULL),
(20, 'Shirtless Woody', 33, 'This giant buildable figure is none other than the legendary Shirtless Woody. Shirtless Woody makes an excellent display piece in any home. He is comprised of 1746 pieces.', '8.00', 'http://rebellug.fetchapp.com/sell/70cb75b2', 'woodymain.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'woody - Joe Minieri.xml', 'true', 5, 'woodymain.png', 'true', 100, NULL),
(21, 'The Old Republic BT-7 Thunderclap', 21, 'The BT-7 Thunderclap or BT-7 Thunderstrike was an assault ship used as a deployment ship by the Republic Military during the Old Republic. It appears in the MMORPG Star Wars: The Old Republic game. This model composed of 2199 pieces, is made at midi-scale to fit with other previously produced LEGO Star Wars UCS models. Regardless of being mainly a display piece it possesses a couple moving features like retractable landing gear, boarding ramp and folding wings for flight/landing modes. It also includes a UCS style stand with custom sticker template so you can display it in flight mode. This model is recommended for advanced and experienced builders as it contains some rather complex building techniques. Note: Yellow parts in the manual can be any color.', '15.00', 'http://rebellug.fetchapp.com/sell/9dcc4fb6', 'BT-7main.JPG', 'thunderclap360.gif', 'thunderclapinstructions.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thunderclap_parts.xml', 'true', 5, 'BT-7main.JPG', 'true', 40, NULL),
(22, 'Victory-Class Imperial Star Destroyer', 21, 'The Victory-class Star Destroyer was a warship used by the Galactic Republic and later on by the Galactic Empire during the Clone Wars and Galactic Civil War (respectively). Measuring barely over half the size of a regular Imperial Star Destroyer, it was mainly used for planetary defense, assault and ship to ship combat.\" This vessel notably appeared in the RTS game Empire at War.\" This MOC composed of 1967 pieces, has an accurate exterior design that makes up a great display model. On top of that it includes moving features like the opening side mandibles, reveiling this ships\' iconic missle launchers. <a href=\"https://youtu.be/afEnV8rjtHA\" target=\"_blank\">Full showcase of the model</a>', '15.00', 'http://rebellug.fetchapp.com/sell/a2e083c7', 'victoryfrontpage.jpg', 'victory-Class Star Destroyer 360 - Andrew Cazenave-Tapie.gif', '_DSC1320 - Andrew Cazenave-Tapie.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'victory-Class Star Destroye_parts.xml', 'true', 4, 'victoryfrontpage.jpg', 'true', 40, NULL),
(23, 'LEGO Halo Warthog', 7, 'The Warthog is a light recon vehicle equipped to fight alien invaders of Earth and her colonies. This model features rolling wheels, seats for two minifigures and one standing in turret, and a rotating machine gun turret. It has the durability to hold together well for light play. The suspension struts may snap with heavy pressure. It does not steer. It has 349 pieces.', '8.00', 'http://rebellug.fetchapp.com/sell/78e61483', 'lego_halo_warthog_1.jpg', 'lego_halo_warthog_2.jpg', 'lego_halo_warthog_3.jpg', 'lego_halo_warthog_4.jpg', 'lego_halo_warthog_5.jpg', NULL, NULL, NULL, NULL, NULL, 'warthog.xml', 'true', 2, 'lego_halo_warthog_cropped.jpg', 'true', 100, NULL),
(24, 'Zapper', 7, 'Zapper add-on to LEGO 71374 Nintendo Entertainment System. Features a moving trigger and a plug that connects to the LEGO NES console. Two sets of instructions are provided for one price to build in either dark bluish gray with red trigger or orange with black trigger.', '12.00', 'http://rebellug.fetchapp.com/sell/3e911063', 'NickBrickNESZapper_Scene_2_NB - Nick Brick.jpg', 'neszapper_outside_01 - Nick Brick.jpg', 'neszapper_outside_02 - Nick Brick.jpg', 'NickBrickNESZapper_360 - Nick Brick.gif', NULL, NULL, NULL, NULL, NULL, NULL, 'zapper/index.html', 'true', 1, 'zappermain.jpg', 'true', 100, NULL),
(25, 'BARC Speeder (Battlepack Alt-Build)', 8, 'A BARC speeder designed as closely to the realistic Star Wars version in size as possible, with the constraint of using only parts found in 2 501st Legion Clone Troopers (75820) sets. The speeder alone contains 66 parts, and the full instructions including a stand and 2 crates contains 91 parts. ', '2.00', 'http://rebellug.fetchapp.com/sell/8c95a6a1', '501st alt BARC speeder v2 rotation animation - Peter Myers.gif', 'BARC Speeder Main Promo Image - Peter Myers.jpg', '501st on speeder - Peter Myers.jpg', '501st alt BARC speeder v2 render_2 - Peter Myers.png', NULL, NULL, NULL, NULL, NULL, NULL, 'Minifigure Scale BARC Speeder 501st Alt build - Peter Myers.xml', 'true', 4, '501st alt BARC speeder v2 render_2 - Peter Myers.png', 'true', 100, NULL),
(26, 'AT-XT Walker', 31, 'The All Terrain Experimental Transport (AT-XT) was an experimental armored assault walker used by the Grand Army of the Republic during the Clone Wars. It was a predecessor to the AT-RT and AT-ST, and was notably deployed during battles on Raxus Prime, Rhen Var, Thule, and Jabiim. The model features a rotatable head, cockpit for a pilot and gunner, posable legs, and contains 338 parts. ', '15.00', 'http://rebellug.fetchapp.com/sell/c22aa037', 'Lego AT-XT Walker - Matt.png', 'AT-XT Walker Cover - Matt.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AT-XT Walker - Matt.xml', 'false', 5, 'AT-XT Walker Cover - Matt.png', NULL, NULL, NULL),
(27, 'Hailfire Droid', 31, 'The IG-227 Hailfire-class droid tank, also known as the Hailfire Droid, was an autonomous wheeled missile platform used by the Confederacy of Independent Systems during the Clone Wars. Initially contributed by the Intergalactic Banking Clan, the vehicles were repainted to match the signature blue and gray color scheme of the CIS after the formal declaration of war with the Galactic Republic. The vehicle sports two missile launcher pods, each with 15 guided warheads (non-removable), as well as a light anti-infantry laser canon. It is designed primarily for display and contains a total of 414 parts.', '10.00', 'http://rebellug.fetchapp.com/sell/e94a1f41', 'Lego Hailfire Droid - Matt.png', 'Hailfire Cover - Matt.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'Hailfire Droid - Matt.xml', 'false', 6, 'Hailfire Cover - Matt.png', NULL, NULL, NULL),
(28, 'BT-7274 Vanguard Titan', 7, 'Minifig-scale model of the Vanguard/Monarch class Titan from Titanfall 2. Instructions, parts lists, and Studio files included for: BT-7274 (dark green), FS-1041 (dark bluish gray), Expedition XO-16 Shorty, Ronin Broadsword, and Legion Predator Cannon. Parts list for pilot Jack Cooper also included. Titan model is intended for display only and has limited posing through articulation in the legs, arms, hands, fingers, \"eye\", and missile pods. Can wield each weapon in an alert stance. Canopy opens to seat a pilot inside.', '10.00', 'http://rebellug.fetchapp.com/sell/2c4820d6', '11 Cooper Out Walking.jpg', 'Nick Brick BT FS Weapons 360 - Nick Brick.gif', '07 Front Right.jpg', '17 Weapons.jpg', '06 Canopy Open.jpg', '18 Jack Cooper.jpg', NULL, NULL, NULL, NULL, 'vanguard/index.html', 'true', 2, '11 Cooper Out Walking.jpg', 'false', 0, NULL),
(29, 'Chess Set', 43, 'A 1:1 scale LEGO chess set to fulfill your desirer to have a chess set made out of LEGO. This model contains 653 pieces.', '10.00', 'http://rebellug.fetchapp.com/sell/bf9765bf', 'Chess_Render - 501stLegoTrooper.gif', 'Chess Set - 501stLegoTrooper.jpeg', 'Chess Render Image 2 - 501stLegoTrooper.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Chess Set xlm File - 501stLegoTrooper.xml', 'true', 5, 'chessmain.jpg', NULL, NULL, NULL),
(30, 'Ahsoka Tano\'s Lightsabers (CW)', 12, 'Build your own life size replica of Ahsoka Tano\'s lightsabers from the Clone Wars (with display stand.)  These are 1:1 replicas recreating all the details seen throughout the Clone Wars.  The models are designed for display, but are sturdy enough to be handled.  You get to build her primary saber and her shōtō saber with a display stand that can hold both.  There are a total of 463 pieces and 100 pages of detailed instructions to make the building process easy.  Instructions and part list are included with purchases, no actual parts are for sale and must be provided or sourced yourself.  All BLUE and WHITE elements in the parts list cannot be seen when the build is complete and therefore any color can be used for those particular elements.', '10.00', 'http://rebellug.fetchapp.com/sell/ff6f6564', 'Brick Ninja Ahsoka Lightsabers Clone Wars GIF - Kevin Wanner.gif', 'Brick Ninja Ahsoka Lightsabers Clone Wars 01 - Kevin Wanner.png', 'Brick Ninja Ahsoka Lightsabers Clone Wars 03 - Kevin Wanner.png', 'Brick Ninja Ahsoka Lightsabers Clone Wars 02 - Kevin Wanner.png', 'Brick Ninja Ahsoka Lightsabers Clone Wars Instruction Sample - Kevin Wanner.png', NULL, NULL, NULL, NULL, NULL, 'Brick Ninja Ahsoka Lightsabers Clone Wars Parts List - Kevin Wanner.xml', 'true', 3, 'Brick Ninja Ahsoka Lightsabers Clone Wars 01 - Kevin Wanner.png', NULL, NULL, NULL),
(31, 'Darth Revan\'s Lightsaber', 21, 'This model is a 1:1 replica of Revan\'s lightsaber from the Star Wars games Knights of the Old Republic (KOTOR) and The Old Republic (SWTOR). It was designed using the recently released Black Series Darth Revan saber hilt as main reference point, and has an approximate length of 37cm / 14.5in. The final result is strong and sturdy enough for it to be wielded and moved around with relative ease. This includes PDF step by step instructions for the lightsaber hilt composed of 654 parts and the base/stand of 293 parts, for a total of 947 pieces. (It costs approximately $120 USD to gather all parts)', '9.00', 'http://rebellug.fetchapp.com/sell/a0d79223', 'Revan lightsaber - Andrew Cazenave-Tapie.gif', 'revan_saber-ig4_alt - Andrew Cazenave-Tapie.jpg', 'revan_saber-ig1 - Andrew Cazenave-Tapie.jpg', 'revan_saber-ig3 - Andrew Cazenave-Tapie.jpg', 'revan_saber-ig2 - Andrew Cazenave-Tapie.jpg', NULL, NULL, NULL, NULL, NULL, 'Revan Saber partlist - Andrew Cazenave-Tapie.xml', 'true', 3, 'revan_cover.jpg', NULL, NULL, NULL),
(32, 'Spaceballs: The Schwartz-Ring', 7, 'What is a good RebelLUG collaboration without a little merchandising? Instructions for a Schwartz-ring just like Lone Starr\'s in Spaceballs. Original build part of Civilized Age: RebelLUG Lightsaber Collab.', '1.00', 'http://rebellug.fetchapp.com/sell/90ea67c2', 'NickBrickLoneStarrRing - Nick Brick.gif', 'CARLLC_NickBrickLoneStarr - Nick Brick.jpg', 'NickBrickLoneStarrRing - Nick Brick.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NickBrickSpaceballsTheSchwartzRingParts - Nick Brick.xml', 'true', 5, 'Ring01 - Nick Brick.jpg', NULL, NULL, NULL),
(33, 'V-19 Torrent and Delta-7B Interceptors', 41, 'Recreate iconic moments from the early days of the Clone Wars with these microscale models of the V-19 Torrent Fighter and Anakin and Obi Wan\'s Delta-7B Interceptors. These models were designed to be scale accurate and mainly intended for display purposes, although they are slightly swooshable. The V-19 features folding wings. A stand is not included to keep the parts list short.', '4.00', 'http://rebellug.fetchapp.com/sell/88d82590', 'Instructions-V19 - Thomas Veerman.gif', 'V-19+delta-shopped-V2 (2) - Thomas Veerman.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Instructions-V19 - Thomas Veerman.xml', 'true', 4, 'V-19+delta-shopped-V2 (2) - Thomas Veerman.png', NULL, NULL, NULL),
(34, 'Maul\'s Lightsaber', 70, 'This is your chance to build a life-size replica of Maul’s lightsaber (including display stand), which he used in his last battle against Obi-Wan Kenobi in the Rebels series. The model is designed for display but is sturdy enough to be handled. Its length is approximately 42 cm / 16.5 in, and it consists of 619 pieces in total (501 for the lightsaber and 118 for the display stand). The instructions included with this purchase are in the form of a PDF that guides you step by step through the building process. Besides the instructions, a parts list is included. No actual pieces are for sale and must be provided or sourced yourself. It costs around 80 USD to gather all pieces.', '8.00', 'http://rebellug.fetchapp.com/sell/53748386', 'JastaBrickMaulsLightsaber - Jan.gif', 'img_1 - Jan.jpg', 'img_2 - Jan.jpg', 'cover - Jan.jpg', NULL, NULL, NULL, NULL, NULL, NULL, 'JastaBrickMaulsLightsaber - Jan.xml', 'true', 3, 'mualsaberthumb.jpg', NULL, NULL, NULL),
(35, 'Aes Sedai Prison Carriage', 12, 'Build your own version of the Aes Sedai prison carriage from the Wheel of Time, and parade a False Dragon through the streets.  This is designed off of the prop from the show while mixed with the description from the book. The carriage has four covered chairs, one for each of the Aes Sesai sisters, one chair for the carriage driver and a spot for the prisoner cage.  The carriage is pulled by 4 horses and the removable cage can hold one prisoner.  The model is primarily designed for display, but is sturdy enough to be handled. There are a total of 542 pieces and 50 pages of detailed instructions to make the building process easy. Instructions and part list are included with purchases, no actual parts are for sale and must be provided or sourced yourself. All RED elements in the parts list cannot be seen when the build is complete and therefore any color can be used for those particular elements.', '5.00', 'http://rebellug.fetchapp.com/sell/cb37475b', 'Aes Sedai Prison Carriage 02 - Rebel LUG.gif', 'Aes Sedai Prison Carriage 01 - Rebel LUG.jpg', 'Aes Sedai Prison Carriage 04 - Rebel LUG.png', 'Aes Sedai Prison Carriage 03 - Rebel LUG.jpg', NULL, NULL, NULL, NULL, NULL, NULL, 'Aes Sedai Prison Carriage Part List - Rebel LUG.xml', 'true', 4, 'Aes Sedai Prison Carriage 01 - Rebel LUG.jpg', NULL, NULL, NULL),
(36, 'Ray Gun', 7, 'One of the original Zombies Wonder Weapons, now in LEGO form. Sturdy enough to be held and gently reloaded. Instructions show how to build the Ray Gun and 4 Atomo Cold Cell batteries only. OInstructions to light up the barrel included. However, lights are OPTIONAL - if you do not wish to light up your Ray Gun, you can build the model without them and skip the wiring steps. Brickstuff items required to light up the barrel: \r\n<a href=\"https://www.brickstuff.com/store/p20/6-inch-cable-4-packs.html\">1x 6\" cable </a>\r\n<a href=\"https://www.brickstuff.com/store/p31/coin-cell-battery-pack.html\">1x Coin Cell Battery Pack</a>\r\n<a href=\"https://www.brickstuff.com/store/p89/lego-cool-white-light-strip-bulk-packs.html\">2x Cool White LED strips </a>', '12.00', 'https://rebellug.fetchapp.com/sell/07c42f5f', 'Nick Brick Ray Gun 360 - Nick Brick.gif', '01 - Nick Brick.jpg', '13 - Nick Brick.jpg', '14 - Nick Brick.jpg', '15 - Nick Brick.jpg', '16 - Nick Brick.jpg', NULL, NULL, NULL, NULL, 'Nick Brick Ray Gun Zombies - Nick Brick.xml', 'true', 1, '01 - Nick Brick.jpg', NULL, NULL, NULL),
(37, 'Airbuster Mech', 12, 'Build your own version of Shinra’s Airbuster Mech from Final Fantasy VII, and try to destroy the members of AVALANCH!  This is designed off of the version from the 2020 remake.  The mech has posable arms, can turn at the waist and adjustable grenade tubes.  The mech comes with a display stand to make it “hover.”  The model is primarily designed for display, but it is sturdy enough to be handled. There are a total of 373 pieces and 125 pages of detailed instructions to make the building process easy. Instructions and part list are included with purchases, no actual parts are for sale and must be provided or sourced yourself. All RED and BLUE elements in the parts list cannot be seen when the build is complete and therefore any color can be used for those particular elements.  This also comes with a FREE digital download for a UCS style plaque.', '5.00', 'https://rebellug.fetchapp.com/sell/0be8d269', 'Airbuster - Rebel LUG.gif', '02 Airbuster - Rebel LUG.jpg', '03 Airbuster - Rebel LUG.jpg', '04 Airbuster - Rebel LUG.jpg', '05 Airbuster - Rebel LUG.jpg', NULL, NULL, NULL, NULL, NULL, 'Airbuster - Rebel LUG.xml', 'true', 1, '02 Airbuster - Rebel LUG.jpg', NULL, NULL, NULL),
(38, 'New Hashima Cube Standard', 72, 'The cube standard for the legendary  <a href=\"https://www.instagram.com/newhashimacollab/\">New Hashima collaboration</a> is now available for free! You can download the <a href=\"https://drive.google.com/file/d/1n_FA0WvQZIYLQMV5-gNJEmCvp0TyQa1a/view?usp=sharing\">PDF Instructions</a> and the <a href=\"https://drive.google.com/file/d/1-HbPY7DA6RnumRsmvihzEIY4WoXPakQB/view?usp=sharing\">Stud.IO file</a> at these links respectively.', 'Free!', NULL, 'nh_cube01.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'nh_cube_standard.xml', 'true', 0, 'nh_cube01.jpg', NULL, NULL, 'true');

-- --------------------------------------------------------

--
-- Table structure for table `members`
--

CREATE TABLE `members` (
  `id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `handle` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `bio` varchar(1000) NOT NULL,
  `pfp` varchar(255) NOT NULL,
  `youtube` varchar(255) DEFAULT NULL,
  `flickr` varchar(255) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `personalSite` varchar(255) DEFAULT NULL,
  `dateJoined` date DEFAULT NULL,
  `manualOrder` int DEFAULT NULL,
  `isMember` varchar(10) DEFAULT NULL,
  `isHighCommand` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `members`
--

INSERT INTO `members` (`id`, `name`, `handle`, `title`, `description`, `bio`, `pfp`, `youtube`, `flickr`, `instagram`, `twitter`, `facebook`, `personalSite`, `dateJoined`, `manualOrder`, `isMember`, `isHighCommand`) VALUES
(1, 'Drew', 'Packer 221', '', '', 'Hey, I’m Drew. I tend to build on the smaller side when it comes to MOCs, which are usually Star Wars themed. What time in the hobby I don’t spend building is dedicated to the seemingly endless process of sorting my parts collection.', 'Packer_221_pfp2.jpg', 'https://www.youtube.com/c/Packer221', 'https://www.flickr.com/photos/145425767@N03/', 'https://instagram.com/packer_221?igshid=1j9duteoki29i', NULL, NULL, NULL, '2016-12-11', NULL, 'true', 'false'),
(2, 'Everette Howard', 'A Brick Interest', '', '', 'I\'m an International relations student at OU and a modern military builder in lego. I\'ve been in the community for over a decade, my biggest inspiration has always been The Purge group on flickr.  Most of what I do is based off of old ways of building factions and crearing storylines for my builds that used to be so popular back on flickr. Outside of lego I lift and I am a combat engineer in the army.', 'A_Brick_Interest_2_pfp.jpg', 'https://youtube.com/channel/UCE9cdA9_Eync3f51CPVRDmA', 'https://www.flickr.com/photos/128358236@N07/', 'https://www.instagram.com/a_brick_interest/', 'https://twitter.com/a_interest', NULL, NULL, NULL, NULL, 'true', 'false'),
(3, 'Danny Dirienzo', 'Lego Buff Productions', 'Board Member and LAN Ambassador', 'Danny is in charge of communication between the LUG and the LEGO® group as well as running the RebelLUG Instructions Store. Danny is a co-founder.', 'Hey, I\'m Danny! I was one of the original founders of RebelLUG and currently spend most of my attention on running the instructions store and communicating with The LEGO Group. I am studying Industrial Engineering with a focus in Economics and Finance and a Business Minor at the University of Illinois. When I am not working on large scale Star Wars bases, I enjoy film production and playing sports. ', 'Lego_Buff_Productions_pfp.jpg', 'https://www.youtube.com/user/Legobuff68', 'https://www.flickr.com/photos/125281213@N08/', 'https://www.instagram.com/legobuffproductions/', NULL, NULL, NULL, NULL, 0, 'false', 'false'),
(4, 'Eli Willsea', 'ForlornEmpire', '', '', 'Hello, my name is Eli Willsea and I have been building with LEGO since.. well... I kinda forget. You can find me building in all sorts of themes and scales but I particularly love microscale. I love a good challenge and usually am participating in contests. I love to collaborate and attend conventions when I am able. My favorite LEGO theme is Aqua Raiders. Other than LEGO I also play frisbee, make videos, and enjoy a good board game.  Oh and my main account is Grant Davis.', 'ForlornEmpire_pfp.jpg', 'https://www.youtube.com/c/EliWillseaVlogs', 'https://www.flickr.com/photos/eliwillsea', 'https://www.instagram.com/forlornempire', NULL, NULL, NULL, '2020-05-09', NULL, 'true', 'false'),
(5, 'Michael Willhoit', 'MijeW', '', '', 'I\'m Michael. I\'ve been on Flickr since 2010 and RebelLUG since 2020. I cut my teeth building cyberpunk and apocalego, and am a serial Brickfair attendee. I\'m also an architect in the state of Pennsylvania. I love this community and all the friends I\'ve made along the way.', 'MijeW_pfp.jpg', NULL, 'https://www.flickr.com/photos/epic-fail-time/', 'https://www.instagram.com/trillhoit/', NULL, NULL, NULL, '2020-07-05', NULL, 'true', 'false'),
(6, 'Tobias Whelan', '[Intense Potato]', '', '', 'I’m an AFOL from Maryland currently studying architecture at Pratt Institute in NYC! LEGO has been a massive part of my life since I can remember, and I love exploring the spaces one may overlook in my builds. Whether those spaces are the overgrown side streets of a quaint town or the peaceful roads winding around a grassy field, I strive to create builds that are both familiar and new! I have lots of experience organizing and contributing to collaborative builds and I can’t wait to work with the RebelLUG gang on some. Thanks for reading! :)', 'Intense_Potato_pfp.jpg', NULL, 'https://www.flickr.com/photos/73042395@N07/', 'https://www.instagram.com/tobias.whelan/', NULL, NULL, NULL, '2020-06-14', NULL, 'true', 'false'),
(7, 'Nick Jensen', 'Nick Brick', '', '', 'There\'s no higher praise for the realism of a LEGO weapon build than Chicago comic-con security confiscating it.', 'Nick_Brick_pfp.jpg', 'https://www.youtube.com/c/nickbrick', 'https://www.flickr.com/photos/nickjensen/', 'https://www.instagram.com/legobynickbrick/', 'https://twitter.com/nickbrickbuilds', 'https://www.facebook.com/legobynickbrick', NULL, '2017-06-19', NULL, 'true', 'false'),
(8, 'Peter', 'Spartan Bricks', '', '', 'Howdy! My name is Peter, and I’m an AFOL from Texas. I’ve been building with LEGO since I was 5 years old and as I have grown up, have grown more captivated by the unlimited creative potential unlockable with LEGO. My chosen career of aerospace engineering has been inspired significantly by my passion for Star Wars and the exploration of space, a passion mirrored in my builds, which are commonly Star Wars scenes. I also enjoy building historical, castle, pirate, and generic space themes, among other things; often simply whatever has captured my imagination at the moment. I plan to perpetually deepen my creative & design skills through LEGO, and with my own creations hope to inspire others to realize their own creative potential. Maranatha!', 'Spartan_Bricks_pfp.jpg', 'https://www.youtube.com/channel/UCX9SjclMhRWC46wpwxqTQxA?view_as=subscriber', 'https://www.flickr.com/photos/153598801@N02/', 'https://www.instagram.com/spartan_bricks/', NULL, NULL, NULL, '2018-06-15', NULL, 'true', 'false'),
(9, 'Ryan McBryde', 'goatman461', '', '', 'Owner of Rogue Brick Builders’ Lounge in Fort Worth TX. ', 'goatman461_pfp.jpg', NULL, 'https://www.flickr.com/photos/goatman461', 'https://instagram.com/goatman461?igshid=flaky5aj1q1l', NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(10, 'Micah Beideman', 'Hacim Bricks', '', '', 'Hello, my name\'s Micah. I have been a fan of LEGO pretty much my entire life, though I\'m currently a college student, so I don\'t get the chance to build as often as I would like. I don\'t have any specific theme I like to build in, but I do enjoy building models from my favorite TV shows. I\'ve been a member of the online LEGO community since 2013 and mainly use Flickr, though I also have an Instagram.\"', 'Hacim_Bricks_pfp.jpg', 'https://www.youtube.com/channel/UCOwyX28E6Bh67oxjScMrtbg', 'https://www.flickr.com/photos/hacimbricks/', 'https://www.instagram.com/hacimbricks/?hl=en', NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(11, 'Spencer Hubert', 'LegoSpencer', 'Board Member, Design Lead, and Web Admin', 'Spencer is in charge of RebelLUG\'s graphics and design needs as well as maintaining the website. Spencer is a co-founder.', 'What\'s up, everyone! The LEGO community\'s been a significant part of the majority of my life thus far and I\'m so glad I belong to it. YouTube\'s definitely my favorite place though (no offense Flickr, Insta, or Reddit crowd), and it\'s where it all started for me, so I try and focus as much on making LEGO videos as making the MOCs themselves. In addition to LEGO, I\'m into filmmaking and computer science, so I try and bring both of those to the LEGO-sphere best I can.', 'LegoSpencer_pfp.jpg', 'https://youtube.com/legospencer11', 'https://www.flickr.com/photos/legospencer11/', 'https://instagram.com/legospencer11', NULL, '', 'https://spencerhubert.info', '2015-12-06', 1, 'true', 'true'),
(12, 'Kevin Wanner', 'Brick Ninja', '', '', 'Hi, I am Kevin (Brick Ninja) and I love creating my own Lego builds. I work mostly on Star Wars and a variety of Castle/Fantasy themes; including Lord of the Rings, Wheel of Time, and Final Fantasy. My online presence is mostly on Flickr and Instagram. When not at work I spend most of my time building and reading, with occasionally drawing and playing videogames.', 'Brick_Ninja_pfp.jpg', 'https://www.youtube.com/channel/UCc8vrx0WQ2EUHJO_guQqsmg', 'https://www.flickr.com/photos/brickninja/', 'https://www.instagram.com/brick.ninja/?hl=en', 'https://twitter.com/The_Brick_Ninja?s=09', NULL, NULL, '2018-07-14', NULL, 'true', 'false'),
(13, 'Timothy Shortell', 'Classical Bricks', '', '', 'Hi, I\'m Timothy! You may also know me as Classical Bricks on Flickr and Instagram. I most enjoy building medieval and Middle-Earth creations in addition to a variety of other themes, or whatever inspires me. I enjoy building large dioramas, small detailed scenes, and everything inbetween. I also love collaborating with other builders and attending LEGO conventions.', 'Classical_Bricks_pfp.jpg', 'https://www.youtube.com/channel/UCzc7gTBTFK-xYlGOAp11iwA', 'https://www.flickr.com/classicalbricks', 'https://www.instagram.com/classicalbricks', NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(14, 'Bryce Dempsey', 'Brickbuilt Replicas', '', '', 'I\'m a California-based Lego builder who recreates video game weapons in 1:1 scale, and loves the color purple. Many of my builds rely upon cool functionality and movable parts, as well as recently branching out to figure building. ', 'Brickbuilt_Replicas_pfp.png', 'https://www.youtube.com/c/brickbuiltreplicas', 'https://www.flickr.com/photos/brickbuiltreplicas/', 'https://www.instagram.com/brickbuilt.replicas', 'https://twitter.com/LegoGamingGuns', 'https://www.facebook.com/brickbuiltreplicas', NULL, '2017-06-18', 10, 'true', 'true'),
(15, 'Hugo', 'Legofrenchbuilder', '', '', 'Hey, my name is Hugo! I\'m a young french engineer living in England since 2 years and I should move to Canada or somewhere else soon.\n\nI started back to be in Lego seriously when I arrived in the UK (after a 14 years break). A Star Wars set brought me back and since then it is my main theme of build even if I try to mix it with historical theme such as the ancient Greece or the middle age....\n\nAs I\'m moving a lot it can be hard for me to keep up the pace as I don\'t have my Lego collection with me every time and it can be hard for me to find the time to build but I\'m doing my best to post content regularly!', 'Legofrenchbuilder_pfp.jpg', 'https://www.youtube.com/channel/UC11M2EtfqpZLKSkBFfdi8WA?', NULL, 'https://www.instagram.com/legofrenchbuilder/', NULL, NULL, NULL, '2020-06-14', NULL, 'true', 'false'),
(16, 'Guillaume Flanquart ', 'T.C.A Production', '', '', 'Hi! I’m an AFOL from France, and a big fan of Star Wars more precisely in the themes The Clone Wars and The Old Republic. I started building MOCs in 2017 and I opened my Bricklink store, named Alphus Store, in 2020. ', 'T.C.A_Production_pfp.jpg', 'https://youtu.be/3qaBOD_J9FE', NULL, 'https://www.instagram.com/tcaproduction/', NULL, NULL, 'https://store.bricklink.com/AlphusStore?p=AlphusStore#/shop?o=%7B%22showHomeItems%22:1%7D', '2018-11-18', NULL, 'true', 'false'),
(17, 'Fin ', 'Legofin.', '', '', 'I joined the Lego community in 2012 and have mostly been active since then, I build from various themes, including but not limited to Cyberpunk, Star Wars, general sci-fi-iness, and in the past castle. Although I still prefer Flickr, I’m currently more active on Instagram.', 'Legofin._pfp.jpg', NULL, 'https://www.flickr.com/photos/legofin/', 'https://www.instagram.com/legofin/?hl=en', NULL, 'https://m.facebook.com/pages/category/Personal-Blog/Legofin/about/', NULL, NULL, NULL, 'true', 'false'),
(18, 'Kaleb', 'llego_pig', '', '', 'My name is Kaleb and I\'m  from Norway. I have built with lego my entire life. Aside  from building with lego I love watching movies and playing videogames, which is what most of my builds are based of.', 'llego_pig_pfp.jpg', 'https://www.youtube.com/channel/UCz2gaHCbrRHqIfGYL8dCClg', 'https://www.flickr.com/people/157104492@N05/', 'https://www.instagram.com/llego_pig/', 'https://twitter.com/LlegoPig', NULL, NULL, '2020-01-04', NULL, 'true', 'false'),
(19, 'Pandelis', 'MalenGarek', '', '', 'Hi, my name is Pande most people know me from my social media name Malen Garek. If I am not running community projects, I build a lot of star wars, apoc, and mocs from other themes. I get burned out by a theme very fast, so I always lookout for new things and themes to build, so make sure to check out my social media!', 'MalenGarek_pfp.jpg', 'https://www.youtube.com/channel/UCqlRsSG_qZGBZWoypUvEJTQ', 'https://www.flickr.com/photos/147752544@N02/', 'https://www.instagram.com/malengarek/?hl=en', 'https://twitter.com/MalenGarek', NULL, NULL, '2019-09-08', NULL, 'false', 'false'),
(20, 'Fabian B.', 'ordo_builds', '', '', 'I\'m Fabian aka ordo_builds. I\'m an AFOL from Germany and started sharing my creations online in 2010. Since then I have kept posting my builds on various platforms. In my builds I mainly focus on the Star Wars franchise, though, I don\'t shy away from dipping into other themes every once in a while. Those mostly include such franchises as Harry Potter or The Legend of Korra, as well as the occasional un-themed build born from pure imagination. With RebelLUG I hope to expand on these themes, find like minded builders and become more active in the community. Beyond the bricks, I am a media designer and cultural science student with a passion for anything creative like drawing, writing and music. ', 'ordo_builds_pfp.jpg', NULL, 'https://www.flickr.com/photos/47697314@N02/', 'https://www.instagram.com/ordo_builds/', NULL, NULL, NULL, '2020-02-10', NULL, 'false', 'false'),
(21, 'Andrew Cazenave-Tapie', 'CRCT Productions', '', '', 'Hey, my name is Andrew Cazenave-Tapie, I\'m a French AFOL currently studying Aerospace engineering. As a long time Star Wars fan I mostly build large/medium scale vehicles and scenes from all types of source materials (legends and canon). I generally try to keep them as accurate as possible while adding some original elements from my own. You can always find me searching for new ways of using certain pieces and new techniques to use in my MOCs.', 'CRCT_Productions_pfp.jpg', 'https://www.youtube.com/channel/UCuImqOKWB6nfWeMN6Udkfjg', 'https://www.flickr.com/people/143572137@N04/', 'https://www.instagram.com/andrew_crctprod/', NULL, NULL, NULL, '2018-08-03', NULL, 'true', 'false'),
(22, 'Lukas ', 'The Brick Puke', '', '', 'Hello, my name is Lukas, otherwise known by my strange Lego username The Brick Puke . I\'m a Swedish custom Lego builder who primarily focuses on different types of Star Wars vehicles. I\'ve been a part of the Lego online community for about 4 years now, but my interest in Lego stretches back far longer than that. ', 'The_Brick_Puke_pfp.jpg', 'https://www.youtube.com/channel/UC593cofm54u1wqQeFZ3Lh7Q', NULL, 'https://www.instagram.com/thebrickpuke/?hl=sv', NULL, NULL, '', '2017-02-11', NULL, 'true', 'false'),
(23, 'Nathaniel', 'NS Brick Designs', '', '', 'Hey guys! Years ago, during my teenage years, I truly discovered the LEGO® brick and the system of creativity that revolves around these plastic elements. LEGO® is not simply a toy for children - it has become an art form all around the world! When I first began building my own creations, I focused mainly on medieval models. Now, I have branched out to basically creating anything and everything, usually things that particularly interest me at the time. Something I always consider is the fact that I am indeed working with a product that was originally created to be a children\'s toy. While I like to consider myself an artist, I always remember the importance of just having fun. Taking your models seriously to a degree is completely understandable, but at the end of the day, joy is an important element. Always remember to \'Play well!\'', 'NS_Brick_Designs_pfp.jpg', NULL, 'https://www.flickr.com/photos/ns_legodesigns/', 'https://www.instagram.com/nsbrickdesigns/', NULL, 'https://www.facebook.com/NSBrickDesigns', 'https://nsbrickdesigns.wixsite.com/nsbrickdesigns', '2018-11-10', NULL, 'false', 'false'),
(24, 'Peter', 'Guy Smiley', '', '', 'I\'m Peter, AKA Guy Smiley on Flickr and more recently, YouTube. I joined Flickr and began my online building career in August 2012. I have built in many different themes, but my favorites are the various subthemes within science-fiction. I began my YouTube channel in 2018 as another place to share my MOCs and grow a new audience. I have since branched out into making other types of LEGO related content. I\'m from San Diego California and am a student at San Diego State University majoring in biology. When I\'m not building LEGO or making videos I\'m either studying or surfing, which has become my other favorite thing to do. ', 'Guy_Smiley_pfp.jpg', 'https://www.youtube.com/guysmiley', 'https://www.flickr.com/photos/builderperson/', 'https://www.instagram.com/guy_smiley_lego/', NULL, NULL, NULL, '2020-06-14', NULL, 'true', 'false'),
(25, 'Cole Blood', 'Cole Blood', '', '', 'Hello There. My name is Cole, and I\'m a FOL based in the great Pacific Northwest of America. I\'ve building for about as long as I can remember and got into the Lego community through mocpages (RIP) while a preteen. Since then I\'ve been hooked. Whether or not I\'m posting a bunch I\'m always looking for new inspiration and fiddling with the bricks.', 'Cole_Blood_pfp.jpg', NULL, 'https://www.flickr.com/photos/153393143@N02/', 'https://www.instagram.com/cole_blood_/', NULL, NULL, NULL, '2020-06-01', NULL, 'false', 'false'),
(26, 'Joel Tyer', 'Jako of Nerogue', '', '', 'Hi I am Joel, I am a Christian builder from Texas. I Generally build either Castle or fantasy mocs but I will occasionally venture out and make something from another genre. Outside of Lego you will probably find me working on school, playing Basketball, or messing around on Age of Empires. ', 'Jako_of_Nerogue_pfp.jpg', NULL, 'https://www.flickr.com/photos/145987998@N02/', 'https://www.instagram.com/jako_of_nerogue/', NULL, NULL, NULL, '2020-01-11', NULL, 'true', 'false'),
(27, 'Wout Gillis', 'WG Productions', '', '', 'Hi people! My name is Wout a.k.a. WG Productions on Flickr and Instagram. I\'m a LEGO builder from Belgium. I have been a LEGO fan for as long as I can remember. I started Flickr back in 2012 and still upload my creations there today! The theme I build the most is Star Wars, but from time to time I also try out other themes that interest me. I just love LEGO in general for the creativity and possibilities you have with it. Keep building everyone!', 'WG_Productions_pfp.jpg', NULL, 'https://www.flickr.com/photos/85985319@N08/', 'https://www.instagram.com/wg_productions_/', NULL, NULL, NULL, '2019-09-11', NULL, 'true', 'false'),
(28, 'Tommy', '-TTROOPER-  ', '', '', 'Hello, my name is Tommy and I\'m an AFOL from the US. I\'ve been building with legos for just about as long as I can remember and joined Flickr in 2012. I\'m a huge fan of Star Wars and fantasy and I love being able to create stories with my builds. Most of my builds revolve around a Clone Wars RPG that I help run with Legion Dude over on flickr, but I\'ll build just about what ever I\'m feeling inspired by. Usually I stick to small 16x16 vignette style builds, but occasionally I\'ll work on something bigger. My other interests include, Warhammer, history, studying for college and just about anything military.', '-TTROOPER-___pfp.jpg', NULL, 'https://www.flickr.com/photos/121068492@N02/', 'https://www.instagram.com/cc_1807/', NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(29, 'Simon Liu', 'Si-MOCs', 'Board Member', '', 'Hey hey! I\'m Simon from Canada, eh. I\'ve kinda done a bit of every type of building at this point, but my favorite themes are Sci-Fi and my specialties are Drones/Mechs. I tend to be involved a lot within the LEGO community: running and competing in many contests/challenges, including being involved with many of RebelLUG\'s contests/challenges. ', 'Si-MOCs_pfp.jpg', 'https://www.youtube.com/channel/UCEopqxSPkbqLoAZDvlrcrtg', 'https://www.flickr.com/photos/si-mocs/', 'https://www.instagram.com/si_mocs', NULL, NULL, 'http://1024words.com/', '2016-06-19', 3, 'true', 'false'),
(30, 'Alec', 'Alec_D', '', '', 'Hey everyone, my name is Alec. I\'m an AFOL that primarily builds Star Wars and Sci-fi MOCs. I build with Lego because I enjoy the challenge it presents. Recreating or designing something new, given the limitations of Lego, is what keeps me coming back. I joined RebelLUG since it is an active community of builders who share common interests. I usually attend Brickworld Chicago and you can find me on Flickr. Happy building everyone!', 'Alec_D_pfp.jpg', NULL, 'https://www.flickr.com/photos/17634665@N07', NULL, NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(31, 'Matt', 'Brick Tale Studios', '', '', '\nMy name’s Matt! I’m a LEGO fan and stop motion animator from Chicago, Illinois, otherwise known as Brick Tale Studios on YouTube, Instagram, and Twitter. I’ve been building with Lego all my life and I’ve been creating Lego stop motion animations (also known as brickfilms) since 2009. Most of my brickfilms are based on franchises like Star Wars and Halo, however lately I’ve been building a lot of 1:48 scale trains my local LEGO train club. When I’m not busy building or animating, I’m probably gaming, out with friends, or just cruisin’ around in my Mustang.', 'Brick_Tale_Studios_pfp.jpg', 'https://www.youtube.com/c/BrickTaleStudios', 'https://www.flickr.com/photos/lswstoriesanimations/', 'https://www.instagram.com/bricktalestudios/', 'https://twitter.com/BrickTaleStudio', NULL, NULL, '2018-06-16', NULL, 'false', 'false'),
(32, 'Caleb Huet', 'LegoHobbitFan', '', '', 'My name is Caleb Huet, although I go by LegoHobbitFan in the Lego community. I am a Christian TFOL, and my favorite themes to build in are castle and fantasy, although I\'ll build just about anything.', 'LegoHobbitFan_pfp.jpg', NULL, 'https://www.flickr.com/people/142810870@N08/', 'https://www.instagram.com/legohobbitfan/', NULL, NULL, 'https://legohobbitbuilder.wordpress.com', '2020-03-14', NULL, 'true', 'false'),
(33, 'Joe', 'jnj_bricks', '', '', 'Hey, I’m Joe! I’ve been building with LEGO most of my life but really got more into the hobby after graduating college in 2019. I enjoy building all sorts of different themes and styles, but my favorite is forced perspective builds. Outside of LEGO, I’m a software developer, Christian, banjo player, and calisthenics enthusiast.  ', 'jnj_bricks_pfp.jpg', NULL, 'https://www.flickr.com/photos/186036005@N06/', 'https://instagram.com/jnj_bricks?igshid=jhnb7iicaoyz', NULL, NULL, NULL, '2020-01-11', 10, 'true', 'true'),
(34, 'Jan', 'Jan, the Creator', '', '', 'Name\'s Jan, Adult Fan Of LEGO (AFOL) from Poland. I mainly build Star Wars and Apoc, but I love to explore new themes such as cyberpunk, medieval, sci-fi etc. Hop in my socials and enjoy!', 'Jan_the_Creator_pfp.jpg', NULL, 'https://www.flickr.com/photos/jan_the_creator/', 'https://www.instagram.com/jan_the_creator/', NULL, NULL, NULL, '2019-08-03', NULL, 'false', 'false'),
(35, 'Justinn Cialini', 'Crimson Bricks', '', '', 'Hey everyone! My name is Justinn and I am a LEGO MOC builder and customiser from NY. I work on a variety of projects mostly from Star Wars however I do cover other themes I love such as Marvel, DC, and Avatar. I also make characters and people I think are cool into LEGO form!', 'Crimson_Bricks_pfp.jpg', 'https://www.youtube.com/user/JecProductions2000', 'https://www.flickr.com/photos/97251304@N08/', 'https://www.instagram.com/thecrimsonbricks/', NULL, NULL, NULL, '2013-04-11', NULL, 'false', 'false'),
(36, 'Jet Ochoa', 'jetbricks', 'Collab Lead and Community Engagement Lead', 'Jet is a collaboration leader, responsible for cultivating engagement with fans of the group, and managing the RebelLUG YouTube channel.', 'Yes, Jet is actually my name, and I joined RebelLUG in August of 2019. I don\'t specialize in any one specific building theme or style, as I enjoy trying out a wide variety of concepts. Most of my LEGO content ends up on YouTube, as the video format adds an extra layer of creativity and complexity. Outside of LEGO, I\'ve continued developing an interest in film, as well as athletics such as swimming and triathlons. Most importantly, RebelLUG is easily my favorite thing that I\'m involved with and I\'m excited to continue my membership in the group.', 'jetbricks_pfp.jpg', 'https://www.youtube.com/c/jetbricks', 'https://www.flickr.com/photos/183143022@N05/', 'https://www.instagram.com/jetbricks/', 'https://twitter.com/JetBricks', NULL, NULL, '2019-08-03', 10, 'true', 'true'),
(37, 'Abe Fortier', 'Hypolite Bricks', '', '', 'Hey my name is Abe! I am a builder from Minnesota who currently lives in Los Angeles, California. I have been building LEGO since I was three years old. I took a small break from LEGO during high school and college. Immediately after graduating college I started building more and becoming more active on Youtube, Flickr, and Instagram. I really starting working on my craft which landed me at RebelLug. I mainly build Star Wars MOCs because I love the lore of Star Wars so much. I am also very interested in building Cyberpunk MOCs and will occasionally challenge myself with new themes if I have the time. My other interests outside of LEGO include writing, film, animation, video editing, and soccer! ', 'Hypolite_Bricks_pfp.jpg', 'https://www.youtube.com/channel/UCkfCU8fPh-DkkGv3maC7aVQ?view_as=subscriber', 'https://www.flickr.com/photos/128605995@N02/', 'https://www.instagram.com/hypolite_bricks/', NULL, NULL, 'https://www.instagram.com/abeyfortier/', '2020-06-14', NULL, 'true', 'false'),
(38, 'Caleb', 'Masked Builder', 'LAN Ambassador', '', 'Hello, I\'m Caleb. I\'ve been building with LEGO since about 2002. If I think something is interesting I will take a stab at building it. As a result I have dabbled in many themes. I\'ve built everything from 14-wide cars, replica weapons, Star Wars ships, to more fantasy style builds. I use flickr some, but it\'s easier to find my stuff at Brickworld Chicago every year.', 'Masked_Builder_pfp.jpg', NULL, 'https://www.flickr.com/photos/masked-builder/', 'https://www.flickr.com/photos/masked-builder/', NULL, NULL, NULL, '2018-08-11', 0, 'true', 'true'),
(39, 'Bart Deliën', 'Barthezz Brick', '', '', 'Hey, my name is Bart in the LEGO community know as Barthezz Brick, and I’m a LEGO builder from The Netherlands. I got back into LEGO early 2017 after a dark age of 20 years and since then I’ve been very active on social media platforms such as Instagram, Flickr, Reddit Facebook, Twitter & YouTube. I love sharing photos of my creations, but most of all I build for fun and my photos are my legacy. My field of expertise is colored. So I build in different styles like; medieval, city, ww2, star wars, fantasy, pirates & zombie/apocalyptic in the years to come.', 'Barthezz_Brick_pfp.jpg', 'https://www.youtube.com/channel/UC7ADd8LQ_Jpxos61ZAQtCFg', 'https://www.flickr.com/photos/151790575@N05/', 'https://www.instagram.com/barthezzbrick/', 'https://mobile.twitter.com/BarthezzB', 'https://m.facebook.com/BarthezzBrick/', 'https://www.barthezzbrick.com', '2019-06-19', NULL, 'false', 'false'),
(40, 'Elijah', 'PeachBricks', '', '', 'Hey hows it going, my name is Elijah and I\'ve been a member of RebelLUG since 2017! I\'ve been a huge fan of LEGO ever since I was a child which carried over into my teen years. Recently due to various life events my LEGO hobby is on hold but I\'ll be back in the future!', 'PeachBricks_pfp.jpg', 'https://www.youtube.com/channel/UCFQD31vuXx9JkJHIJwSPhmA?view_as=subscriber', 'https://www.flickr.com/photos/peachisdank/', 'https://www.instagram.com/peachbricks/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(41, 'Thomas Veerman', 'LegionDude', '', '', 'I have been posting my MOC\'s on Flickr since 2011, mainly building Clone Wars vignettes but dabbling in modern/futuristic military stuff as well. Most of my builds are contributions to the 253rd Legion RPG group, where I\'m also an admin. I study Earth Science at Utrecht University in the Netherlands. ', 'LegionDude_pfp.jpg', NULL, 'https://www.flickr.com/photos/253dlegionguy/', 'https://www.instagram.com/legiondude/', NULL, NULL, NULL, '2017-07-21', NULL, 'true', 'false'),
(42, 'James', 'Legomania', '', '', 'Hey, I’m James! I’m a builder from Oregon who builds in a very wide variety of themes, with the main themes and things I build being sci-fi, mechs,, apoc and scenes. I’m always trying to expand what I build, so it’s not uncommon to see lots of other stuff from me too as I experiment. Outside of LEGO, I have many other interests and hobbies, including volunteering at my church, listening to music, photography, sports, as well as hiking and other outdoor activities. I try to stay as active as I can in the community, going to my local conventions of Bricks Cascade and BrickCon, and I\'m always happy to chat online!', 'Legomania_pfp.jpg', 'https://www.youtube.com/channel/UC63t4g9qSrQLB5mhbqPbj3Q', 'https://www.flickr.com/photos/79012179@N04/', 'https://www.instagram.com/legomania211/', NULL, NULL, NULL, '2019-02-09', NULL, 'true', 'false'),
(43, 'Daniel Barwegen', 'Daniel Barwegen', '', '', 'I\'m an AFOL from Canada. I started off on Youtube building only Star Wars MOCs, but over the last few years I have tried my hand at many different themes. As an architecture student many of my mocs have been focused around buildings, from Dutch architecture and modern house designs to post-apocalyptic wastelands.', 'Daniel_Barwegen_pfp.jpg', NULL, 'https://www.flickr.com/photos/132542949@N05/', 'https://www.instagram.com/daniel_barwegen/?hl=en', NULL, NULL, NULL, '2015-08-01', NULL, 'true', 'false'),
(44, 'Grant Davis', 'Grant Davis', '', '', 'Hi my name is Grant Davis and I play with plastic bricks on the regular to help justify the room they take up at my parents house. I have been building for 8 years now in every genre that you can think of, though I still have a soft spot in my heart for Star Wars, the Lord of the Rings and Pirate mocs. Though I\'ve recently been trying to improve in areas outside of my comfort zone such as Bionicle and Technic. My greatest achievement is building a LEGO popup book that some people on LEGO Ideas liked enough to turn into an official set.', 'Grant_Davis_pfp.jpg', 'https://www.youtube.com/channel/UCGH4o7taGSE-4FB8ZzJxhkA?view_as=subscriber&sub_confirmation=1', 'https://www.flickr.com/photos/93970753@N05/', 'https://www.instagram.com/grantdvs1/?hl=en', NULL, 'https://www.facebook.com/grantdavisbricks', NULL, '2017-06-06', NULL, 'false', 'false'),
(45, 'Finn Benischek', 'Mr.MOCsProductions', '', '', 'Hey, I’m Finn. Lego is one of the many things I do to pass the time in the small Alaskan town of Talkeetna. Other than that I spend most of my time dirt biking up and down a highway (very fun) and downhill skiing. Peace.', 'Mr.MOCsProductions_pfp.jpg', 'https://www.youtube.com/c/MrMOCsProductionsRebellug', 'https://www.flickr.com/photos/183455890@N03/', 'https://instagram.com/mr.mocsproductions?igshid=1tgfunvm9qz5o', NULL, NULL, NULL, '2017-06-14', NULL, 'true', 'false'),
(46, 'Yannis Rosse ', 'YR_Bricks ', '', '', 'Hi, I am an afol from Germany and build mostly apocalyptic stuff and Star Wars. I love to go on conventions such as Bricking Bavaria and I am always down to try new stuff. Sadly my Wifi is really bad so I only post on Instagram although I\'d like to have a YouTube channel in the future. ', 'YR_Bricks__pfp.jpg', NULL, NULL, 'https://instagram.com/yr_bricks?igshid=198wk42sqzw5u', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(47, 'Caleb Walker ', 'Elven Ranger ', 'Collab Lead', 'Caleb is a collaboration leader.', 'Hey there, I’m Caleb! I am a pilot-in-training who loves the LEGO brick.\nSome of my favorite themes include; the Hobbit + the Lord of the Rings and Star Wars. I really like building rockwork and I try to add as much detail as possible into my builds.', 'Elven_Ranger__pfp.jpg', 'https://m.youtube.com/channel/UCpP8hnPjAehUiNWTUJ-BtvA', 'https://www.flickr.com/photos/elvenranger', 'https://www.instagram.com/elven.ranger/', NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(48, 'Luca', 'Luca s projects', '', '', 'Hey, my name is Luca. I\'m a builder from Germany, these days I\'m mostly focused on recreating Star Wars vehicles in LEGO. I joined the community back in 2017 on Flickr and have been building ever since. It usually takes me ages to finish projects but sometimes I also participate in contests and challenges. I attend a few conventions as well, mostly here in Germany. You can find my builds on my Flickr account.', 'Luca_s_projects_pfp.jpg', 'https://www.youtube.com/Lucasprojects', 'https://www.flickr.com/photos/luca_s_projects/', 'https://www.instagram.com/luca_s_projects/', 'https://twitter.com/Luca_s_projects', NULL, NULL, '2019-07-13', NULL, 'true', 'false'),
(49, 'Wyatt', 'wmxproductions', '', '', 'Hey, I’m Wyatt. I’m an AFOL from Chicago and I’ve loved Lego as long as I can remember. I usually enjoy building 19th-20th century historical models but also like building Star Wars from time to time. My favorite thing about building Lego is that the sky is the limit, and you can really build whatever you want with it.', 'wmxproductions_pfp.jpg', 'https://www.youtube.com/channel/UC11-Fb-akyci3x1OJOnzR6Q?view_as=subscriber', 'https://www.flickr.com/photos/147266144@N08/', 'https://www.instagram.com/wmxproductions/?hl=en', NULL, NULL, NULL, '2018-05-13', NULL, 'false', 'false'),
(50, 'Noah', 'h2brick', 'Board Member and Operations Lead', 'Noah is responsible for organizing, managing, and leading a committee related to the logistics of LUG assets, such as sponsorship material or bulk product ordering.', 'Hello there, I’m Noah! Using this artistic medium loved by many, I assemble models and scenes from mostly the science fiction realm, primarily Star Wars with some recent dabbles into Cyberpunk. Additionally, I also bring my creations to a number of conventions around the world, Bricking Bavaria, BrickWorld Chicago and Skærbæk Fan Weekend to name a few. As a member of RebelLUG, I run operations like the 2HR Monthly Challenge and coordinate European RL convention gatherings.', 'h2brick_pfp.jpg', 'https://m.youtube.com/user/h2brick', 'https://www.flickr.com/photos/145675635@N03/', 'https://www.instagram.com/h2brick/?hl=en', 'https://mobile.twitter.com/lego_designer?lang=en', 'https://m.facebook.com/pages/category/Artist/h2brickoffical/posts/?locale2=de_DE', NULL, '2016-12-10', 3, 'true', 'true'),
(51, 'Anders', 'Alcloneproductions', '', '', 'I’ve been in this LUG a while. I used to build a lot of Star Wars, now I build whatever. People say I like to build rocks.', 'Alcloneproductions_pfp.jpg', 'https://www.youtube.com/c/alcloneproductions', NULL, 'http://instagram.com/alcloneproductions/', NULL, NULL, NULL, '2015-11-22', NULL, 'false', 'false'),
(52, 'Jake Hansen', 'Mountain Hobbit', '', '', 'Hi, my name is Jake and I\'m a Lego builder from Oregon. I\'ve made a lot of fantasy/castle creations in the past, but recently I have enjoyed branching out and just building whatever inspires my creativity. ', 'Mountain_Hobbit_pfp.jpg', NULL, 'https://www.flickr.com/photos/148658905@N06/', 'https://www.instagram.com/mountainhobbit/', NULL, NULL, NULL, '2020-01-11', NULL, 'true', 'false'),
(53, 'Alexander', 'dogma54', '', '', 'My name is Alexander and I am a lego enthusiast from Germany. I specialized in building Star Wars Mocs but I am also doing other themes like Apoc, Cyberpunk and Military. I get my inspiration mostly from Movies, Books or Pictures.\nI joined the online Lego community in 2017.', 'dogma54_pfp.jpg', 'https://www.youtube.com/channel/UCN3xYb6RTelKOvNmGTwhK8g/about', 'https://www.flickr.com/photos/187925672@N07', 'https://www.instagram.com/dogma_54/', NULL, NULL, NULL, '2019-07-14', NULL, 'true', 'false'),
(54, 'Olav', 'Norlego', '', '', 'Hey, my name is Olav, and I’m a LEGO builder from Norway. I got back into LEGO building around early 2016 and since then I’ve been very active on social media platforms such as Instagram, Flickr and Youtube. I love sharing pictures of my creations not only when they’re completed, but also during the building process. My field of expertise has grown to become Lord of the Rings and Star Wars, but I also enjoy building MOCs based on themes like Pirates and Castle.', 'norlego_pfp.jpg', 'https://www.youtube.com/user/norlego', 'https://www.flickr.com/photos/150874663@N02/', 'https://www.instagram.com/norlego/', 'https://twitter.com/norlego', NULL, NULL, NULL, NULL, 'true', 'false'),
(55, 'Luka', 'First Order Lego', 'Social Media Curator', 'Luka is responsible for currating the RebelLUG feed and managing our presense on social media.', 'This is Luka, I\'m an active MOC builder known for my mid scale Star Wars dioramas, but I do meddle in other themes quite often. I post on most social medias, but YouTube is my main focus. You have probably seen some of my building timelapses on there. I\'ve been building since I was a kid and never stopped. Currently I study visual design in Croatia, but I\'m a born Aussie. Conventions with the LUG are always year hightlights :D', 'First_Order_Lego_pfp.jpg', 'https://www.youtube.com/channel/UCZ5mlcNske2N68vxc4vi5Aw', 'https://www.flickr.com/photos/157923275@N05/', 'https://www.instagram.com/firstorderlegos/?hl=en', 'https://twitter.com/FirstOrderLego', NULL, NULL, '2016-08-14', 10, 'true', 'true'),
(56, 'Lee', 'Brick Builder Studios', '', '', '', '', 'https://www.youtube.com/channel/UCm4s-wYBHsfZlfHhivUtTjw', 'https://www.flickr.com/photos/143944724@N04/', 'https://instagram.com/brickbuilderstudios', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(57, 'Kris', 'Krisproductions', '', '', '', '', 'https://www.youtube.com/user/krisproductionstudio', 'https://www.flickr.com/photos/52927377@N02/', 'https://www.instagram.com/krisproductions', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(58, 'Josh', 'BrickMaster Productions', '', '', '', '', 'https://www.youtube.com/channel/UCnm_nTOHJg4VJ7c26tS8Okw', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(59, 'Connor', 'FyXIT Bricks', '', '', '', '', 'https://www.youtube.com/user/LegoLord82', 'https://www.flickr.com/photos/99733081@N05/', 'https://www.instagram.com/fyxit_bricks/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(60, 'Emeth', 'e__meth', '', '', '', '', NULL, NULL, 'https://www.instagram.com/e__meth/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(61, 'Alex', 'The Brick Den', '', '', '', '', 'https://www.youtube.com/channel/UCTAtrsFXL4IsHSGF1bkWp0Q', 'https://www.instagram.com/the_brick_den/', 'https://www.flickr.com/photos/151589681@N04/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(62, 'Aasmund Gabestad Nørsett', 'Northern Lego', '', '', 'My name is Aasmund and I\'m a 16 year old, Norwegian LEGO builder. I\'ve collected LEGO since I was three years old, but only started building MOCs about 2 years ago. I enjoy building Star Wars, Lord of the Rings and Medieval MOCs, but occasionally I build other themes such as City and Pirates of the Caribbean.', '', 'https://www.youtube.com/channel/UCWAAJQbQuZiWoK-7JJ6_IrA', 'https://www.flickr.com/photos/145356369@N04/', 'https://www.instagram.com/northern_lego/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(63, 'Adam', 'CBBricks', '', '', '', '', 'https://www.youtube.com/user/maceprimus321', NULL, 'https://www.instagram.com/cbbricks/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(64, 'Victor', 'CDL Studios', '', '', '', '', 'https://www.youtube.com/user/98csi', 'https://www.flickr.com/photos/83766152@N02/', 'https://www.instagram.com/cdlstudios/', NULL, 'https://www.facebook.com/Kamino-industry-284006035134014/', 'https://www.kaminoindustry.com/', NULL, NULL, 'false', 'false'),
(65, '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(67, 'Tristan', 'TrisBrick', '', '', '', '', NULL, 'https://www.flickr.com/photos/156101416@N07/', NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(68, 'Josh', 'LegoLogical', '', '', '', '', 'https://www.youtube.com/channel/UC6YvZUWooSK2Gs5tkx6v05A', NULL, 'https://www.instagram.com/legological/', NULL, NULL, NULL, NULL, NULL, 'false', 'false'),
(69, 'Sondre', 'Sonseth_Brix', '', '', 'Hi! My name is Sondre and I’m from Norway. I build mostly larger LEGO Star Wars MOCs. My favorite part of Star Wars has to be the Clone Wars. Why I like LEGO so much, is because I love to create stuff and tell my own story. The attention to detail is one of my favorite things about LEGO and what you can recreate with the bricks. I joined RebelLUG in early 2019 and I have grown so much as a builder after that. I’ve also got a lot of new friends in the LEGO community. ', 'Sonseth_Brix_pfp.jpg', 'https://www.youtube.com/channel/UC6a1WFfKL4joGZ4M-qe7w6Q?view_as=subscriber', 'https://www.flickr.com/photos/157611963@N07/', 'https://www.instagram.com/sonseth_brix/', NULL, NULL, NULL, '2019-04-29', NULL, 'true', 'false'),
(70, 'Jan', 'JastaBrick', '', '', 'Hello there, my name is Jan and I’m an AFOL from Switzerland. After a long break from LEGO, I joined the community in early 2020 and joined RebelLUG the following fall. I mainly build Star Wars related MOCs, but sometimes I dive into other themes, like science fiction, medieval, or fantasy. I like to participate in collabs, RPGs and attend conventions.', 'jastabrick_pfp.jpg', 'https://www.youtube.com/channel/UCjpVp741n-OfL9fqZBcMQ3w', 'https://www.flickr.com/photos/187213881@N03/', 'https://www.instagram.com/jastabrick/', 'https://twitter.com/JastaBrick', NULL, NULL, NULL, NULL, 'true', 'false'),
(71, 'Mark', 'Simulterious', '', '', 'Mark here, I enjoy making all sorts of things – from dragons and sky ships to distant worlds and so much more! I’m mainly on Flickr and Instagram. I enjoy working on RebelLUG collaborations and projects. Planning on attending more conventions, catch you there!', 'simulterious.png', NULL, 'https://www.flickr.com/people/154679240@N02/', 'https://www.instagram.com/simulterious1/', NULL, NULL, NULL, NULL, NULL, 'true', 'false'),
(72, 'Stefan Formentano', 'stefanbuildslego', '', '', '', 'stefanbuildslego.jpg', NULL, NULL, 'https://www.instagram.com/stefanbuildslego/', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `collaborations`
--
ALTER TABLE `collaborations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `contests`
--
ALTER TABLE `contests`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `instructions`
--
ALTER TABLE `instructions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `members`
--
ALTER TABLE `members`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `collaborations`
--
ALTER TABLE `collaborations`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `contests`
--
ALTER TABLE `contests`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `instructions`
--
ALTER TABLE `instructions`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- AUTO_INCREMENT for table `members`
--
ALTER TABLE `members`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=74;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
